version: '3'

services:
  web:
    build: ./dockerfiles/web
    container_name: reveltest
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ".:/go/src/github.com/jiro4989/reveltest"
    entrypoint: "revel run -a github.com/jiro4989/reveltest"

